import React from 'react';
import Head from 'next/head';

const Privacypolicy = () => {
    return (
        <>
            <Head>
                <title>Privacy Policy - Shopnation.in</title>
                <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0" />
            </Head>
            <main>
                <section id='tcs'>
                    <h1 className='text-4xl font-bold text-center mt-10'>Privacy Policy</h1>
                    <div className='flex m-auto justify-start items-start flex-col gap-2 mt-5 max-w-[80%]'>
                        <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
                        <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
                    </div>
                    <div className='flex flex-col gap-2 max-w-[80%] justify-start items-start m-auto mt-4'>
                        <p className='text-3xl font-semibold '>Interpretation and Definitions</p>
                        <p className='text-xl font-semibold'>Interpretation</p>
                        <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                    </div>
                    <div className='flex flex-col gap-2 max-w-[80%] justify-start items-start m-auto mt-4'>
                        <p className='text-xl font-semibold'>Definitions</p>
                        <p>For the purposes of this Privacy Policy:</p>
                        <ul className=' justify-start items-start list-none'>
                            <li><span className='font-bold'>Account</span> means a unique account created for You to access our Service or parts of our Service.</li>
                            <li><span className='font-bold'>Company</span> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Shponation, Jammu, J&K.</li>
                            <li><span className='font-bold'>Cookies</span> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
                            </li>
                            <li><span className='font-bold'>Country</span> refers to: Uttar Pradesh, India</li>
                            <li><span>Device</span>means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                            <li><span className='font-bold'>Personal Data</span> is any information that relates to an identified or identifiable individual.

                                Service refers to the Website.</li>
                            <li><span className='font-bold'>Service Provider</span> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                            <li><span className='font-bold'>Third-party Social Media Service</span> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
                            <li><span className='font-bold'>Usage Data</span> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                            <li><span className='font-bold'>Website</span> refers to Shopnation, accessible from https://www.shopnation.in</li>
                            <li><span className='font-bold'>You</span> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                        </ul>
                    </div>
                    <div className='flex flex-col gap-2 max-w-[80%] justify-start items-start m-auto mt-4'>
                        <p className='text-3xl font-semibold'>Collecting and Using Your Personal Data</p>
                        <p className='font-semibold text-2xl'>Types of Data Collected</p>
                        <p className='font-semibold text-xl'>Personal Data</p>
                        <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                        <ul>
                            <li>Email address</li>
                            <li>First name and last name</li>
                            <li>Phone number</li>
                            <li>Address, State, Province, ZIP/Postal code, City</li>
                            <li>Usage Data</li>
                        </ul>

                        <p className='text-xl font-semibold'>Usage Data</p>
                        <ul>
                            <li>Usage Data is collected automatically when using the Service.</li>
                            <li>Usage Data may include information such as Your Device&quot;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</li>
                            <li>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</li>
                            <li>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</li>
                        </ul>
                    </div>
                    <div className='flex flex-col gap-2 max-w-[80%] justify-start items-start m-auto mt-4'>
                        <p className='text-2xl font-semibold'>Use of Your Personal Data</p>
                        <p>The Company may use Personal Data for the following purposes:</p>
                        <ul>
                            <li><span className='font-bold'>To provide and maintain our Service</span>, including to monitor the usage of our Service.</li>
                            <li><span className='font-bold'>To manage Your Account:</span> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
                            <li><span className='font-bold'>For the performance of a contract:</span> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                            <li><span className='font-bold'>To contact You:</span> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&apos;s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
                            <li><span className='font-bold'>to provide you</span> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
                            <li><span className='font-bold'>To manage Your requests:</span> To attend and manage Your requests to Us.</li>
                            <li><span className='font-bold'>For business transfers:</span> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
                            <li><span className='font-bold'>For other purposes:</span> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.

                                We may share Your personal information in the following situations:</li>
                            <li><span className='font-bold'>With Service Providers: </span> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
                            <li><span className='font-bold'>For business transfers:</span> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company ass ets, financing, or acquisition of all or a portion of Our business to another company.</li>
                            <li><span className='font-bold'> With Affiliates:</span>We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
                            <li><span className='font-bold'>With business partners:</span> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
                            <li><span className='font-bold'>With other users:</span> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.</li>
                            <li><span className='font-bold'>With Your consent: </span>We may disclose Your personal information for any other purpose with Your consent.</li>
                        </ul>
                    </div>
                    <div className='flex flex-col gap-2 max-w-[80%] justify-start items-start m-auto mt-4'>
                        <p className='text-2xl font-semibold'>Retention of Your Personal Data</p>
                        <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
                        <p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>
                    </div>
                    <div className='flex flex-col gap-2 max-w-[80%] justify-start items-start m-auto mt-4'>
                        <p className='text-2xl font-semibold'>Transfer of Your Personal Data</p>
                        <p>Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
                        <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
                        <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
                    </div>
                    <div className='flex flex-col gap-2 max-w-[80%] justify-start items-start m-auto mt-4'>
                        <p className='text-2xl font-semibold'>Disclosure of Your Personal Data</p>
                        <p className='text-xl font-semibold'>
                        Business Transactions
                        </p>
                        <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
                        <p className='text-xl font-semibold'>
                        Law enforcement
                        </p>
                        <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
                    </div>
                    <div className='flex flex-col gap-2 max-w-[80%] justify-start items-start m-auto mt-4'>
                        <p className='text-2xl font-semibold'>Security of Your Personal Data</p>
                        <p>
                        The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                        </p>
                    </div>
                    <div className='flex flex-col gap-2 max-w-[80%] justify-start items-start m-auto mt-4'>
                        <p className='text-2xl font-semibold'>Link to Other Websites</p>
                        <p>
                        Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy of every site You visit.
                        </p>
                        <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
                    </div>
                    <div className='flex flex-col gap-2 max-w-[80%] justify-start items-start m-auto mt-4'>
                        <p className='text-2xl font-semibold'>Changes to this Privacy Policy</p>
                        <p>
                        We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
                        </p>
                        <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.

You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
                    </div>
                    <div className='flex flex-col gap-2 max-w-[80%] justify-start items-start m-auto mt-4'>
                        <p className='text-2xl font-semibold'>Contact Us</p>
                        <p>
                        If you have any questions about this Privacy Policy, You can contact us:

By visiting this page on our website: https://www.shopnation.in/contact
                        </p>
                    </div>

                </section>
            </main>
        </>
    )
}

export default Privacypolicy